<Project Sdk="Microsoft.NET.Sdk.Razor">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <RootNamespace>Opx.MudBlazor.FlatUi.Sample</RootNamespace>
    <AssemblyName>Opx.MudBlazor.FlatUi.Showcase</AssemblyName>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Opx.MudBlazor.FlatUi" Version="2.1.3" />
    <PackageReference Include="Microsoft.AspNetCore.Components.Authorization" Version="10.0.11" />
    <PackageReference Include="Microsoft.AspNetCore.Components.Web" Version="10.0.11" />
    <PackageReference Include="Microsoft.AspNetCore.WebUtilities" Version="10.0.11" />
    <PackageReference Include="MudBlazor" Version="9.9.0" />
  </ItemGroup>

</Project>
