<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <BlazorDisableThrowNavigationException>true</BlazorDisableThrowNavigationException>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\src\Opx.MudBlazor.FlatUi\Opx.MudBlazor.FlatUi.csproj" />
    <PackageReference Include="MudBlazor" Version="9.7.0" />
  </ItemGroup>

</Project>
